name: Deploy via FTP Sync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: IshanFx/ftp-deploy-action@v2 # An alternative lightweight engine
        with:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server: ${{ secrets.FTP_SERVER }}
          local_dir: ./
          # Use your hosting account's primary IP address as the FTP_SERVER secret
