name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main # Change to 'master' if your default branch uses that name

jobs:
  web-deploy:
    name: Sync Files
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        
      - name: 📂 Sync files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Exclude configuration files, node modules, or git metadata from transferring
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
